repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          [
            --check,
            --verbose
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [ --check ]


  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.8
        additional_dependencies:
          - flake8-bugbear==23.3.23
          - flake8-commas==2.1.0
          - flake8-comprehensions==3.11.1
          - flake8-builtins==2.1.0
          - flake8-quotes==3.3.2
          - flake8-string-format==0.2.3
          - pep8-naming==0.13.3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: b176ead
    hooks:
      - id: mypy
        args:
          [
            --warn-redundant-casts,
            --warn-unused-ignores,
            --check-untyped-defs,
            --no-implicit-reexport,
            --disallow-untyped-defs
          ]
        additional_dependencies:
          - pydantic
          - httpx
          - pytest_httpx
