repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black . --check
        types: [ python ]
        language: system
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort . --check
        types: [ python ]
        language: system
        pass_filenames: false

      - id: flake
        name: flake8
        entry: flake8 .
        types: [ python ]
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy .
        types: [ python ]
        language: system
        pass_filenames: false
