repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          [
            --check,
            --verbose
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [ --check ]


  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: b176ead
    hooks:
      - id: mypy
        args:
          [
            --warn-redundant-casts,
            --warn-unused-ignores,
            --check-untyped-defs,
            --no-implicit-reexport
          ]
        additional_dependencies:
          - pydantic
          - httpx
          - pytest_httpx
