name: Autorelease

on:
  pull_request:
    types: [ closed ]

jobs:
  autorelease:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install

      - name: Run autorelease
        run: python3 auto_release.py --github_token ${{ secrets.GITHUB_TOKEN }} --current_branch ${{ steps.extract_branch.outputs.branch }}

