name: Autorelease

on:
  pull_request:
    types: [ closed ]
    branches: [ master, v2 ]

jobs:
  autorelease:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.16' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          version: 2.20.1

      - name: Install dependencies
        run: pdm install -dG release

      - name: Run autorelease
        run: >
          pdm run .github/scripts/autorelease.py
          --github_token ${{ secrets.GIT_TOKEN }} --current_branch ${{ github.base_ref }}

