name: Linters

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run black
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "==23.1.0"

      - name: Run isort
      - uses: isort/isort-action@master
        with:
          options: "--check"
          version: "==5.12.0"